server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mylibrary?useUnicode=true&serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: classpath:com.huang.manager.pojo
  configuration:
    map-underscore-to-camel-case: true

#    分页设置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

